substitutions:
  _TERRAFORM_VERSION: 1.3.6

steps:
  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    env:
      - GOOGLE_PROJECT=$PROJECT_ID
      - GOOGLE_REGION=$LOCATION
    args:
      - init
      - -backend-config=bucket=$PROJECT_ID-tfstate
      - -backend-config=prefix=$REPO_NAME

  - name: hashicorp/terraform:$_TERRAFORM_VERSION
    env:
      - GOOGLE_PROJECT=$PROJECT_ID
      - GOOGLE_REGION=$LOCATION
    args:
      - apply
      - -auto-approve
      - -parallelism=1000
